### ISSUE TITLE
Neccessary files not copied to  build directory (Nuget package)

### ISSUE THREAD

**Issue by pde-cds** [AmpScm/SharpSvn#17] opened 2021-07-26 13:46 UTC
On build the referenced Resource SharpPlink-Win32.svnExe is not copied to the build directory when using the nuget package
This file is need by SharpSvn.dll which is correctly copied to build folder.

Used package: https://www.nuget.org/packages/SharpSvn/1.14001.54
My Project is a .Net Framework 4.5

**Comment by rhuijben** [comment] 2021-08-03 10:37
Thanks for reporting. Note that this file is not strictly necessary to use SharpSvn. This file is only used when using svn+ssh:// connections in plink mode. SharpSvn also has an libssh2 mode that doesn't require the file at all. (And all other repository access protocols don't require either of these)

**Comment by pde-cds** [comment] 2021-08-03 11:28
I'm aware of this but inside the SharpSVN.dll the SharpPlink-Win32.svnExe is referenced as Resource so this reference must be copied to the build folder.
![image](https://user-images.githubusercontent.com/61505382/128007889-02d81149-fd4a-4b72-ba28-f4258b5893ec.png)

**Comment by klacol** [comment] 2021-11-14 09:30
Any solution on this?

**Comment by klacol** [comment] 2021-11-14 09:32
I have tried this packages:

- SharpSvn.1.8-x86
- SharpSvn.1.8-x64
- SharpSvn.1.9-x86
- SharpSvn.1.9-x64

The errors stays the same.

**Comment by klacol** [comment] 2021-11-14 09:43
The file SharpPlink-x64.svnExe is part of the nuget-package, but it is not extracted into the bin folder, when the nuget package is installed.

**Comment by klacol** [comment] 2021-11-14 09:53
I have extracted the file `SharpPlink-x64.svnExe` manually from the nuget package and stored it in the root of my project. In the file properties, I have configured: "Copy always". Then the file is copied always to the bin folder and I can compile successfully.

This is a dirty workaround and does not fix the problem at the root cause.

**Comment by rhuijben** [comment] 2022-01-14 15:44
This issue should now be fixed in the nuget package for 1.14001.132. There is a now a .targets file that should copy the file for you with your project.

**Closed by rhuijben** 2022-01-14 15:44 UTC
